export const moviesData = [
  {
    _id: '1',
    title: '33 слова о дизайне',
    link: 'https://www.youtube.com/watch?v=5ovzC93EneA',
    duration: '1ч 30м',
  },
  {
    _id: '2',
    title: '33 слова о дизайне',
    link: 'https://www.youtube.com/watch?v=5ovzC93EneA',
    duration: '1ч 30м',
  },
  {
    _id: '3',
    title: '33 слова о дизайне',
    link: 'https://www.youtube.com/watch?v=5ovzC93EneA',
    duration: '1ч 30м',
  },
  // {
  //   _id: '4',
  //   title: '33 слова о дизайне',
  //   link: 'https://www.youtube.com/watch?v=5ovzC93EneA',
  //   duration: '1ч 30м',
  // },
  // {
  //   _id: '5',
  //   title: '33 слова о дизайне',
  //   link: 'https://www.youtube.com/watch?v=5ovzC93EneA',
  //   duration: '1ч 30м',
  // },
  // {
  //   _id: '6',
  //   title: '33 слова о дизайне',
  //   link: 'https://www.youtube.com/watch?v=5ovzC93EneA',
  //   duration: '1ч 30м',
  // },
  // {
  //   _id: '7',
  //   title: '33 слова о дизайне',
  //   link: 'https://www.youtube.com/watch?v=5ovzC93EneA',
  //   duration: '1ч 30м',
  // },
  // {
  //   _id: '8',
  //   title: '33 слова о дизайне',
  //   link: 'https://www.youtube.com/watch?v=5ovzC93EneA',
  //   duration: '1ч 30м',
  // },
  // {
  //   _id: '1',
  //   title: '33 слова о дизайне',
  //   link: 'https://www.youtube.com/watch?v=5ovzC93EneA',
  //   duration: '1ч 30м',
  // },
  // {
  //   _id: '2',
  //   title: '33 слова о дизайне',
  //   link: 'https://www.youtube.com/watch?v=5ovzC93EneA',
  //   duration: '1ч 30м',
  // },
  // {
  //   _id: '3',
  //   title: '33 слова о дизайне',
  //   link: 'https://www.youtube.com/watch?v=5ovzC93EneA',
  //   duration: '1ч 30м',
  // },
  // {
  //   _id: '4',
  //   title: '33 слова о дизайне',
  //   link: 'https://www.youtube.com/watch?v=5ovzC93EneA',
  //   duration: '1ч 30м',
  // },
  // {
  //   _id: '5',
  //   title: '33 слова о дизайне',
  //   link: 'https://www.youtube.com/watch?v=5ovzC93EneA',
  //   duration: '1ч 30м',
  // },
  // {
  //   _id: '6',
  //   title: '33 слова о дизайне',
  //   link: 'https://www.youtube.com/watch?v=5ovzC93EneA',
  //   duration: '1ч 30м',
  // },
  // {
  //   _id: '7',
  //   title: '33 слова о дизайне',
  //   link: 'https://www.youtube.com/watch?v=5ovzC93EneA',
  //   duration: '1ч 30м',
  // },
  // {
  //   _id: '8',
  //   title: '33 слова о дизайне',
  //   link: 'https://www.youtube.com/watch?v=5ovzC93EneA',
  //   duration: '1ч 30м',
  // },
];
